export const AllRoutes = {
  Home: "/",
  About: "/about",
  Contact: "/contact",
  Courses: "/courses",
  CourseDescription: "/course/description",
  SignUp: "/signup",
  Login: "/login",
  CreateCourse: "/course/create",
  UserProfile: "/user/profile",
  Denied: "/denied",
  NotFound: "*",
  Checkout: "/checkout",
  CheckoutSuccess: "/checkout/success",
  CourseLectures: "/course/lectures",
  AddLecture: "/course/add-lecture",
  AdminDashboard: "/admin/dashboard",
  TutorCourses: "/tutor/courses",
};
